language: rust
sudo: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libopenblas-dev
      - liblapack-dev

rust:
  - stable
  - beta
  - nightly

before_script:
  - cd ${TRAVIS_BUILD_DIR}/faiss-sys && ./travis/install_faiss_c.sh
  - sudo cp $HOME/.faiss_c/libfaiss_c.so /usr/local/lib/
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/:/usr/local/lib/

script:
  - cd ${TRAVIS_BUILD_DIR}/faiss-sys && cargo test
  - cd ${TRAVIS_BUILD_DIR} && cargo test

env:
matrix:
  allow_failures:
    - rust: nightly
