name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
    steps:
    - uses: actions/checkout@v2
    - name: Download and install Faiss
      run: ./faiss-sys/ci/install_faiss_c.sh
    - name: Build
      env:
        LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$HOME/.faiss_c
      run: cargo build --verbose
    - name: Run tests
      env:
        LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$HOME/.faiss_c
      run: cargo test --verbose
